cargo-features = [ "per-package-target" ]

[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
default-target = "wasm32-unknown-unknown"

[workspace]
members = [ "api", "src-tauri", "tauri-interop", "tauri-interop-macro" ]
resolver = "1"

[dependencies]
api = { path = "./api", default-features = false, features = [ "wasm" ]}
wasm-bindgen-futures = { version = "0.4" }
wasm-bindgen = { version = "0.2" }
js-sys = "0.3.65"

console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.20"
gloo-timers = "0.3.0"
serde-wasm-bindgen = "0.6.1"
serde = { version = "1.0.193", features = ["derive"] }
