[workspace]
members = [ "tauri-interop-macro" ]
package.edition = "2021"
package.version = "1.3.0"
package.keywords = [ "wasm", "tauri", "command", "event", "leptos" ]
package.authors = [ "photovoltex" ]
package.repository = "https://github.com/photovoltex/tauri-interop.git"
package.license = "MIT OR Apache-2.0"

[package]
edition.workspace = true
version.workspace = true
keywords.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

name = "tauri-interop"
description = "Easily connect your rust frontend and backend without writing duplicate code."
readme = "README.md"

[dependencies]
tauri-interop-macro = { path = "./tauri-interop-macro" }
# tauri-interop-macro = "1.2.0"

js-sys = "0.3.65"
serde = { version = "1.0.193", features = ["derive"] }
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.38"
thiserror = "1.0.50"
serde-wasm-bindgen = "0.6.1"
log = "0.4.20"

# leptos feature
leptos = { version = "0.5.2", optional = true }

# only include if not wasm
[target.'cfg(not(target_family = "wasm"))'.dependencies]
tauri = { version = "1.5.2", default-features = false, features = ["wry"] }

[target.'cfg(target_family = "wasm")'.dependencies]
tauri-interop-macro = { path = "./tauri-interop-macro", features = [ "wasm" ] }
# tauri-interop-macro = { version = "1.2.0", features = [ "wasm" ] }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tauri = "1.5.2"

[features]
# todo: remove default feature before publish
default = [ "event" ]
event   = [ "tauri-interop-macro/event" ]
leptos  = [ "dep:leptos", "tauri-interop-macro/leptos" ]
# used to generated the missing documentation only generated for "target_family = wasm"
wasm    = []
