[package]
name = "tauri-interop-macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = [ "full" ]}
quote = "1.0"
convert_case = "0.6.0"
lazy_static = "1.4.0"
