name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu

    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Run tests for crate
      run: cargo test --verbose

    - name: Build test-project (wasm)
      run: |
        cd test-project
        cargo build --verbose --target wasm32-unknown-unknown

    - name: Build test-project (host)
      run: |
        cd api
        cargo build --verbose --target x86_64-unknown-linux-gnu
